# Generated by Django 4.0.1 on 2022-01-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly', '0003_alter_post_pub_date_alter_reply_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='building',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
