# Generated by Django 4.0.1 on 2022-01-28 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly', '0005_remove_extenduser_id_extenduser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighborly.building'),
        ),
    ]
