# Generated by Django 4.0.1 on 2022-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly', '0008_extenduser_occupants_addrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='occupants',
            field=models.ManyToManyField(blank=True, to='neighborly.ExtendUser'),
        ),
    ]
