# Generated by Django 4.0.1 on 2022-01-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly', '0009_alter_extenduser_occupants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dfuyivvod/image/upload/v1643411157/media/uploads/profile_pictures/default_mme7ds.png', upload_to='uploads/profile_pictures'),
        ),
    ]
