# Generated by Django 4.0.1 on 2022-01-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly', '0010_alter_extenduser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures'),
        ),
    ]
